<?php

namespace Database\Seeders\Admin;

use Illuminate\Database\Seeder;
use App\Models\Admin\PaymentGateway;
use App\Models\Admin\PaymentGatewayCurrency;

class PaymentGatewaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        //gateway
        $payment_gateways = array(
            array('id' => '1','slug' => 'add-money','code' => '105','type' => 'AUTOMATIC','name' => 'Paypal','title' => 'Paypal Gateway','alias' => 'paypal','image' => '056c00f2-b983-499f-b53e-c27d66410866.webp','credentials' => '[{"label":"Secret ID","placeholder":"Enter Secret ID","name":"secret-id","value":"EOmsQW73ja4jFXUIpkeTuKj5qLcqiXRCPZMPx-2UNzNy729C5lzN8cYIdZRfHIx7xPVh9cyaeByefXJL"},{"label":"Client ID","placeholder":"Enter Client ID","name":"client-id","value":"AZhkSGtOqSoGsixors18c5UDkmHD53TzNogt2ksVfxqDeu1RzqdjMClVv8VGarayaAH1exMK0JHMjE8v"}]','supported_currencies' => '["USD","AUD","CAD","GBP","SGD","BRL","EUR","RUB"]','crypto' => '0','desc' => NULL,'input_fields' => NULL,'env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '2','slug' => 'add-money','code' => '106','type' => 'AUTOMATIC','name' => 'Stripe','title' => 'Stripe Gateway','alias' => 'stripe','image' => '25cc3ebb-13cb-4aa9-83df-77ebf1e8a785.webp','credentials' => '[{"label":"Publishable Key","placeholder":"Enter Publishable Key","name":"publishable-key","value":"pk_test_51JAfGoGegh5E3HUjZ1VadWf7TGX0FVyQh0wspFL5AYjUU2q8ZUI3rjN8MNUtiFLPBgculGZz5OujWJHwVwY7EXs400kbWEmzAv"},{"label":"Secret Id","placeholder":"Enter Secret ID","name":"secret-id","value":"sk_test_51JAfGoGegh5E3HUjyGksfy3Z8iRdVre6zfXiVkBFklcddV19Uh1UcSd7KiKiVa2tGrVgcOj8Xp60B1XC0UoguKPa00vMw4kl4o"}]','supported_currencies' => '["USD","AUD","AED","BDT","BGN","CAD","EGP","EUR","GBP","INR"]','crypto' => '0','desc' => NULL,'input_fields' => NULL,'env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '3','slug' => 'add-money','code' => '110','type' => 'MANUAL','name' => 'AdPay','title' => 'AdPay Gateway','alias' => 'adpay','image' => '6fe0ddbe-9c0c-4326-95bd-29ac7711b649.webp','credentials' => NULL,'supported_currencies' => '["USD"]','crypto' => '0','desc' => '<p>This is the manual payment gateway for StripCard, Please follow the payment instruction and sumit required information.</p>.','input_fields' => '[{"type":"file","label":"Screenshoot","name":"screenshoot","required":true,"validation":{"max":"10","mimes":["jpg","png","webp","svg"],"min":0,"options":[],"required":true}},{"type":"text","label":"Transaction ID","name":"transaction_id","required":true,"validation":{"max":"50","mimes":[],"min":"0","options":[],"required":true}}]','env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '4','slug' => 'add-money','code' => '115','type' => 'MANUAL','name' => 'Bkash','title' => 'Bkash Gateway','alias' => 'bkash','image' => '7bee42e7-b1e9-4fe4-8db8-973b859babc7.webp','credentials' => NULL,'supported_currencies' => '["BDT"]','crypto' => '0','desc' => '<p>This is the manual payment gateway for StripCard, Please follow the payment instruction and sumit required information.</p>.','input_fields' => '[{"type":"text","label":"Transaction ID","name":"transaction_id","required":true,"validation":{"max":"100","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Phone Number","name":"phone_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshoot","name":"screenshoot","required":true,"validation":{"max":"2","mimes":["jpg"," png"," webp"," jpeg"],"min":0,"options":[],"required":true}}]','env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '5','slug' => 'add-money','code' => '120','type' => 'MANUAL','name' => 'Khalti','title' => 'Khalti Gateway','alias' => 'khalti','image' => '774e5db2-b461-4285-ad64-1caf6e5a0716.webp','credentials' => NULL,'supported_currencies' => '["NPR"]','crypto' => '0','desc' => '<p>This is the manual payment gateway for StripCard, Please follow the payment instruction and sumit required information.</p>.','input_fields' => '[{"type":"text","label":"Transaction ID","name":"transaction_id","required":true,"validation":{"max":"100","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Phone Number","name":"phone_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshoot","name":"screenshoot","required":true,"validation":{"max":"2","mimes":["jpg"," png"," webp"," jpeg"],"min":0,"options":[],"required":true}}]','env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '6','slug' => 'add-money','code' => '125','type' => 'MANUAL','name' => 'JazzCash','title' => 'JazzCash Gateway','alias' => 'jazzcash','image' => 'c42ea4db-5067-4dda-92a1-4e00f20b5aaf.webp','credentials' => NULL,'supported_currencies' => '["PKR"]','crypto' => '0','desc' => '<p>This is the manual payment gateway for StripCard, Please follow the payment instruction and sumit required information.</p>.','input_fields' => '[{"type":"text","label":"Transaction ID","name":"transaction_id","required":true,"validation":{"max":"100","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Phone Number","name":"phone_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshoot","name":"screenshoot","required":true,"validation":{"max":"2","mimes":["jpg"," png"," webp"," jpeg"],"min":0,"options":[],"required":true}}]','env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '7','slug' => 'add-money','code' => '130','type' => 'MANUAL','name' => 'EasyPaisa','title' => 'EasyPaisa Gateway','alias' => 'easypaisa','image' => '957603b7-d30a-4b70-b4d1-81d8c67ba751.webp','credentials' => NULL,'supported_currencies' => '["PKR"]','crypto' => '0','desc' => '<p>This is the manual payment gateway for StripCard, Please follow the payment instruction and sumit required information.</p>.','input_fields' => '[{"type":"text","label":"Transaction ID","name":"transaction_id","required":true,"validation":{"max":"100","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Phone Number","name":"phone_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshoot","name":"screenshoot","required":true,"validation":{"max":"2","mimes":["jpg"," png"," webp"," jpeg"],"min":0,"options":[],"required":true}}]','env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '8','slug' => 'add-money','code' => '135','type' => 'MANUAL','name' => 'PhonePe','title' => 'PhonePe Gateway','alias' => 'phonepe','image' => 'd6dcbd50-d68e-4535-ae2f-c35e3eb56872.webp','credentials' => NULL,'supported_currencies' => '["INR"]','crypto' => '0','desc' => '<p>This is the manual payment gateway for StripCard, Please follow the payment instruction and sumit required information.</p>.','input_fields' => '[{"type":"text","label":"Transaction ID","name":"transaction_id","required":true,"validation":{"max":"100","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Phone Number","name":"phone_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshoot","name":"screenshoot","required":true,"validation":{"max":"2","mimes":["jpg"," png"," webp"," jpeg"],"min":0,"options":[],"required":true}}]','env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '9','slug' => 'add-money','code' => '140','type' => 'MANUAL','name' => 'UPI','title' => 'UPI Gateway','alias' => 'upi','image' => '80c9caa2-abc3-48c6-b239-778f10888632.webp','credentials' => NULL,'supported_currencies' => '["INR"]','crypto' => '0','desc' => '<p>This is the manual payment gateway for StripCard, Please follow the payment instruction and sumit required information.</p>.','input_fields' => '[{"type":"text","label":"Transaction ID","name":"transaction_id","required":true,"validation":{"max":"100","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Phone Number","name":"phone_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshoot","name":"screenshoot","required":true,"validation":{"max":"2","mimes":["jpg"," png"," webp"," jpeg"],"min":0,"options":[],"required":true}}]','env' => NULL,'status' => '1','last_edit_by' => '1','created_at' => '2023-08-29 13:14:57','updated_at' => NULL)
          );
          PaymentGateway::insert($payment_gateways);

          //gateway currency
          $payment_gateway_currencies = array(
            array('id' => '1','payment_gateway_id' => '1','name' => 'Paypal USD','alias' => 'add-money-paypal-usd-automatic','currency_code' => 'USD','currency_symbol' => '$','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '1.00000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '2','payment_gateway_id' => '1','name' => 'Paypal AUD','alias' => 'add-money-paypal-aud-automatic','currency_code' => 'AUD','currency_symbol' => '$','image' => NULL,'min_limit' => '15.00000000','max_limit' => '1500.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '1.55000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '3','payment_gateway_id' => '2','name' => 'Stripe USD','alias' => 'add-money-stripe-usd-automatic','currency_code' => 'USD','currency_symbol' => '$','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '1.00000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '4','payment_gateway_id' => '2','name' => 'Stripe AUD','alias' => 'add-money-stripe-aud-automatic','currency_code' => 'AUD','currency_symbol' => '$','image' => NULL,'min_limit' => '15.00000000','max_limit' => '1500.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '1.55000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '5','payment_gateway_id' => '3','name' => 'AdPay USD','alias' => 'adpay-usd-manual','currency_code' => 'USD','currency_symbol' => '$','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '1.00000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '6','payment_gateway_id' => '4','name' => 'Bkash BDT','alias' => 'bkash-bdt-manual','currency_code' => 'BDT','currency_symbol' => '৳','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '109.13000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '7','payment_gateway_id' => '5','name' => 'Khalti NPR','alias' => 'khalti-npr-manual','currency_code' => 'NPR','currency_symbol' => 'रु','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '132.05000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '8','payment_gateway_id' => '6','name' => 'JazzCash PKR','alias' => 'jazzcash-pkr-manual','currency_code' => 'PKR','currency_symbol' => 'रु','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '303.16000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '9','payment_gateway_id' => '7','name' => 'EasyPaisa PKR','alias' => 'easypaisa-pkr-manual','currency_code' => 'PKR','currency_symbol' => 'रु','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '303.16000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '10','payment_gateway_id' => '8','name' => 'PhonePe INR','alias' => 'phonepe-inr-manual','currency_code' => 'INR','currency_symbol' => '₹','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '82.67000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL),
            array('id' => '11','payment_gateway_id' => '9','name' => 'UPI INR','alias' => 'upi-inr-manual','currency_code' => 'INR','currency_symbol' => '₹','image' => NULL,'min_limit' => '10.00000000','max_limit' => '1000.00000000','percent_charge' => '1.00000000','fixed_charge' => '2.00000000','rate' => '82.67000000','created_at' => '2023-08-29 13:14:57','updated_at' => NULL)
          );
          PaymentGatewayCurrency::insert($payment_gateway_currencies);

    }
}
